### ISSUE TITLE
ENH: Pulling State info for each event and including with description

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#104]
## Expected Behavior
We would love it if the state abbreviation could be listed in front of each description pulled.

For example:
(DC) Explore Rock Creek...
(VA) Join us for...
(MD) Take a tour...

## Current Behavior
Some events have the States listed, but we noticed some of the NPS events did not have them

## Context
We feel it would be helpful if when viewing the calendar event descriptions that seeing the location (State) up front would be helpful. We will test to see if we can search the calendar by (DC), etc.

**Comment by bmvoss** [comment]
@csmcallister  In the most recent scrape (7/29/19), some Event Sources have the state abbreviation added to the Event Description but many do not. The ones that still don't have this are:

- NPS (National Park Service)
- Audubon Naturalist Society
- Casey Trees
- City Blossoms - many events are also showing "see event website" as the Venue, possibly because the Venue name is buried in the text of the Event Description, although there is an address on the event website in a distinct field
- Friends of Kenilworth Gardens
- Sierra Club
- The Nature Conservancy (Virginia)
- Virginia Native Plant Society

Is it possible/feasible to add this feature for these sources?

**Comment by csmcallister** [comment]
It's gonna take me some time to improve upon the current method. I basically need to look at each event scraper and come up with some custom logic. To help me prioritize the most important event sources, could you sort that list of event sources by their priority?

Unfortunately, I'm heading to 🇮🇹 next week until the end of the month for a family vacation. I doubt I'll be able to get all of these before then.

**Comment by csmcallister** [comment]
> * City Blossoms - many events are also showing "see event website" as the Venue, possibly because the Venue name is buried in the text of the Event Description, although there is an address on the event website in a distinct field

Looking back at those months, there's no consistent way to scrape the venue name from the event website when it isn't provided by their API. I can get the street address reliably, but the *free* reverse geocoding libraries don't provide the venue name when you do a look up with a street address. Luckily, all of the months since last July haven't had events where the venue name wasn't provided by the API.

**Comment by csmcallister** [comment]
@akaahanui To help me prioritize the most important event sources that need descriptions that start with the state abbreviation, could you prioritize the event sources?

**Comment by Frankie-Figz** [comment]
@csmcallister @akaahanui For all events that are registered in eventbrite I made sure  to add the state as requested in this issue.

**Comment by akaahanui** [comment]
@csmcallister Sorry for the delay!

Looking at Britta's list, I'd say these are priorities:

    NPS (National Park Service)
    Audubon Naturalist Society
    Virginia Native Plant Society
    Casey Trees
 Sierra Club (these tend to be multiple states)
   
Less important:
    Friends of Kenilworth Gardens
   The Nature Conservancy (Virginia)

Hope this helps!

Thanks,
Ana

**Comment by csmcallister** [comment]
Issue cleaning...closing for now.
