### ISSUE TITLE
ENH: New event source - Maryland Native Plant Society

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#105]
## Expected Behavior
Scrape events from Maryland Native Plant Society
https://mdflora.org/calendar

**Comment by chungkim271** [comment]
Can you guys assign this to me?

**Comment by csmcallister** [comment]
Sure thing @chungkim271 👏

**Comment by chungkim271** [comment]
@csmcallister, question: it seems like there isn't a sure procedure to grab the 'category', 'cost', and 'description' fields because these aren't in specific locations in html or have specific classes, if mentioned at all on the event page. For example, an event page might say it's a free event but others don't mention costs at all. Is it better for my functions to make the best guess with the event page text or to return empty values if the fields aren't well defined on the page? 

examples: https://mdflora.org/event-3626348?CalendarViewType=1&SelectedDate=2/27/2020, https://mdflora.org/event-3680819?CalendarViewType=1&SelectedDate=1/24/2020

**Comment by csmcallister** [comment]
Hi @chungkim271. These are common issues, so thanks for asking!

Making a best guess is good imo. 

For event descriptions, I've found success selecting the longest <p> element to get the event description. 

As for the cost, I've searched all the text within an area for the word "free" and also used a regular expression to find currency values. If multiple currency values are found, I'll use the largest value. If none are found, I'd just use an empty string, which is still valid for this [field](https://github.com/DataKind-DC/capital-nature-ingest/blob/master/event_schema.md). 

As for the Event Category, you can actually leave that blank if you can't find anything. I just noticed that the schema documentation doesn't make this clear, so thanks again for asking!

**Comment by chungkim271** [comment]
Thanks, @csmcallister. I'll see what I can do!

**Comment by Frankie-Figz** [comment]
Hello @chungkim271 maybe we can collaborate on this issue?

**Comment by csmcallister** [comment]
closed by 7d65ad8
