### ISSUE TITLE
ENH: The battlefield issue: Requesting certain parks to be removed from NPS scrape 

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#106]
## Expected Behavior
If possible, we'd like to see events from these NPS parks:
Rock Creek Park
Kenilworth Aquatic Gardens
Ft Dupont Park
Glen Echo Park
Wolf Trap
Anacostia Park

Did not know how to update the event sources template here:
https://github.com/DataKind-DC/capital-nature-ingest/blob/master/event_sources.md

## Context
Please let me know if this request is not possible.

**Comment by csmcallister** [comment]
If these are in fact National Park Service parks, they should be included with the NPS event source handler because we use their API to fetch all events from all parks within VA, DC and MD. It could be that these venues simply don't report events that are made available through the API. Or something insidious could be going on. 

### Proposed Solution
I can get a list of the parks that the NPS API supports to see if these parks are included. If they are, we'll need to do some research to see what's going on. If they're not, then we'll need to treat them as separate event sources with their own dedicated scrapers.

**Comment by csmcallister** [comment]
@akaahanui here's a spreadsheet with the 80 DMV national parks. 

[dmv_national_parks.xlsx](https://github.com/DataKind-DC/capital-nature-ingest/files/3390161/dmv_national_parks.xlsx)

All of the parks that you listed are in there. If events aren't showing up for one of those parks, it could be the case that the National Park Service isn't inserting those events into their database. From what I've been able to gather, if the event has a page on the NPS website (see this [example](https://www.nps.gov/planyourvisit/event-details.htm?id=777675CF-E666-D3A4-B956061B9F306D79)), then that event should also be in their API. 

Additionally, since I've got this spreadsheet, **feel free to identify any parks that you would never want us to scrape.**

**Comment by csmcallister** [comment]
@akaahanui Could you please identify the park codes, if any, that you would never want us to scrape. This would be any easy fix if I just knew which park codes to exclude.

**Comment by akaahanui** [comment]
@csmcallister Sorry for the delay! We are making a list. I was still checking the distances on some of them. I should be able to send in the next day or so.

**Comment by akaahanui** [comment]
@csmcallister I audited the NPS list and finished looking up distances and drives times to ones I was not familiar with. Please exclude the ones in yellow and scrape the white ones. The oranges ones cover alot of states and I wanted to get your thoughts. We could keep them and manually delete the far away events when we curate or just exclude those parks. Thoughts? Perhaps we try keeping them and see how much work it is to cull distant events. Thanks!

[dmv_national_parks_Capital Nature.xlsx](https://github.com/DataKind-DC/capital-nature-ingest/files/4175134/dmv_national_parks_Capital.Nature.xlsx)

**Comment by csmcallister** [comment]
@akaahanui Let's keep the orange and white for now, and see how much manual curation will be needed to exclude the very distant events from the orange parks. If it's too much work, then we can come back and exclude the orange ones as well.

**Comment by csmcallister** [comment]
96e3214 filters out those yellow parks. We can re-open and revisit this issue in the future if needed.
