### ISSUE TITLE
ENH: New event source: Plant NOVA Natives

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#170]
## Event Source Calendar

https://www.plantnovanatives.org/copy-2-of-event-calendar

## Context
This would be nice to have.  We see there is only one applicable event in December ( a tour).

**Comment by csmcallister** [comment]
@akaahanui 

There are a few issues with this event source.

1. Many of the events lack an event website, which is a required field. And when an event website is present, it's a link to the Virginia Native Plant Society (vnps), which is an event source we are already scraping.

2. The calendar loads dynamically, so scraping it will be tricky (but probably not impossible).

3. Some events lack a description

Due to these issues, I don't think this is something that actually needs scraping. If you agree, we can close the issue.

![Screen Shot 2020-01-10 at 8 46 36 PM](https://user-images.githubusercontent.com/33464354/72197037-ed9bdc80-33ea-11ea-8b08-33e4d10a518b.png)
![Screen Shot 2020-01-10 at 8 46 45 PM](https://user-images.githubusercontent.com/33464354/72197038-ed9bdc80-33ea-11ea-9833-dcf06a419be9.png)

**Comment by csmcallister** [comment]
Closing!
