### ISSUE TITLE
ENH: New event source: Potomac Appalachian Trail Club

### ISSUE THREAD

**Issue by csmcallister** [DataKind-DC/capital-nature-ingest#196]
## Event Source Calendar
https://www.patc.net/PATC/Calendar/PATC/Custom/Calendar.aspx?hkey=9fc06544-1c54-4a47-9efc-8fcd2420a646

## Context
@akaahanui This one wasn't on your list, but it looks like a good match for Capital Nature. What do you think?

## Are we scraping it?

**Comment by Frankie-Figz** [comment]
@minh5 Can we scrape it?

**Comment by akaahanui** [comment]
@minh5 Looks like a promising one. One question - is there a way to filter events so that we don't get the events from PA and further out from DC? (about 80 miles)  For example, we've been excluding Harper's Ferry, Shenandoah Valley and Richmond events from the National Park Service scrapes.

If we identified the parks/trails close enough, listed here:
https://www.patc.net/PATC/WHO_WE_ARE/PATC/Who_We_Are/Who_We_Are.aspx?hkey=96819443-af09-4571-86e8-921c2571b329

could we filter for those, or would that be too much to code? Thanks!

@csmcallister

**Comment by csmcallister** [comment]
Issue cleaning...closing for now.
