### ISSUE TITLE
BUG: Audubon Naturalist Society scraper not pulling all events

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#246]
**Expected Behavior**
The Audubon Naturalist Society scraper not pulling all events. Please scrape their event calendar: https://anshome.org/events-calendar/

**Current Behavior**
Fraction of their events being pulled with existing scraper. We are current through September, so this would be a fix for Oct moving forward.

**Possible Solution**
Scrape the event calendar.

**Context**
This is an important event source for CN, so prioritize.

**Comment by csmcallister** [comment]
This event scraper will automatically attempt to go out 3 months from the current month to get events (e.g. if today is September, it will try to scrape October, November and December). The issue with the missing events is that they don't have clearly listed venues, which is a required field. The scrapers automatically kick out events missing required fields in order to prevent problems when y'all upload the data in CSV format. Two examples of events with hard-to-discern or missing venue info are [this one](https://anshome.org/events/hoa-advocacy-101-nov2020/) and [this one](https://anshome.org/events/thrive-2050-at-ans-2/).

For other event sources such as Casey Trees, Arlington County and Fairfax County, we use a dummy value for the venue if we cannot find one scraping: `"See event website"`. @akaahanui would you like to use `See event website` for those cases, like the two linked above, where scraping the event venue isn't feasible?

**Comment by akaahanui** [comment]
Thanks Scott! I like your suggestion. I have forwarded to Stella and I'll
get back to you tomorrow.

With Aloha,
Ana [image: ]

Capital Nature <http://www.capitalnature.org/>
Follow us on Facebook <https://www.facebook.com/capitalnaturedc/>
Submit an event
<https://docs.google.com/forms/d/e/1FAIpQLSfeTlhA7VbpGqVcIEeujEArEbF7LNyyQ0TkF5dmjA126TbCOQ/viewform>
for
our calendar!

**Comment by csmcallister** [comment]
@akaahanui any word from Stella?

**Comment by akaahanui** [comment]
@csmcallister HI Scott - I haven't heard, so let's proceed as you suggested. Thanks!
