### ISSUE TITLE
BUG: Rock Creek Conservancy returning errors

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#247]
Expected Behavior
Would like to update current scrape from the Rock Creek Conservancy (RCC) event calendar: https://www.rockcreekconservancy.org/what-we-do/upcoming-events

Current Behavior
The RCC scraper is pulling events but with errors:
1) Start and end times are the same
2) Descriptions cut off

Possible Solution
Adjust coding for pulling start and end times
Adjust coding so full description is pulled

Context
This is an important event source for CN, so prioritize.

**Comment by csmcallister** [comment]
@akaahanui 

I checked the logs for this one in yesterday's scrape and there was only one warning, which was for an event that didn't have a venue listed, which is a required field. As a result, we skip that event.

As for the url you provided above, we've been using `https://events.time.ly/8ib56fp`, which seems to have the same events listed as the url you provided.

If you'd like, I can suppress that warning about missing venues so that we get a clean report for this event source. Or am I missing something?

**Comment by akaahanui** [comment]
@csmcallister HI Scott - Yes, please suppress the missing venues as you suggest. With all the virtual events happening, I'm wondering if we should make that adjustment for all scrapes? Thanks!
