### ISSUE TITLE
FIX: NPS schema updates

### ISSUE THREAD

**Issue by bmvoss** [DataKind-DC/capital-nature-ingest#68]
There are some issues with the names of Organizers and Venues and event start and end times from National Park Service sources in the csv output.

## Expected Behavior

- [x] Events at the `Venue` **Greenbelt Park** need to distinguish between the Ranger Station or Sweetgum Picnic Area. The options are:
- Greenbelt Park, Ranger Station
- Greenbelt Park, Sweetgum Picnic Area

- [x] Events at the `Venue` **National Mall and Memorial Parks** should have a more specific `Organizer`, i.e. 'National Park Service, National Mall and Memorial Parks', and then the Venue should be more specific, e.g. 'Martin Luther King Jr. Memorial' or 'World War II Memorial' or 'Franklin Delano Roosevelt Memorial'

- [x] Events at the `Venue` **Oxon Cove Park & Oxon Hill Farm** should be more specific, the options are:
- Oxon Cove Park & Oxon Hill Farm, Dairy Barn
- Oxon Cove Park & Oxon Hill Farm, Oxon Cove Park
- Oxon Cove Park & Oxon Hill Farm, Oxon Hill Farm
- Oxon Cove Park & Oxon Hill Farm, Oxon Hill Farm Visitor Barn
- Oxon Cove Park & Oxon Hill Farm, The Mount Welby Farmhouse at Oxon Hill Farm

- [x] Events at the `Venue` **Rock Creek Park** should have the `Organizer` 'National Park Service, Rock Creek Park', and then the Venue should be more specific, e.g.
- Rock Creek Park Nature Center and Planetarium
- Peirce Mill

- [x] There's a problem with the `start and end times` of NPS events. A lot of events are shown starting at 1:00 AM or 4:00 AM, etc.

## Context
We need to make sure the Organizers and Venues in the Events csv output match corresponding names in the Organizer and Venues csv files.

**Comment by csmcallister** [comment]
I think all these issues are soluble. I'll take a stab soon.

**Comment by csmcallister** [comment]
@bmvoss RE: the first three check-boxes, getting a more specific `Event Venue Name` is going to be difficult to perfect. The ones that have been specific so far are so because the API was being kind. For the others, I'd need to scrape the event's website, which *usually* has a more specific location. But even if there's a more specific location, the chief issue is that the `Location` section of the html sometimes has a lot of extra text that we wouldn't want (see [this](https://www.nps.gov/planyourvisit/event-details.htm?id=AE234152-D067-3570-4EDF0CAB41F2F275) for an example) and I can't think of a programmatic way to reliably parse out the location. Any approach I create now would be overfit, inevitably resulting in a lot of bogus info for the event venues in the future. That would mean you'd have to notify me of every quirk, which I'd then have to incorporate into an ever-growing event-location parser. We *could* do this, but I think it would be a lot simpler if we just use the name of the park for all of the venues, leaving the `Event Organizer` as the National Park Service. Each event has a website, so folks can always get more detailed information about the location there.

**Comment by bmvoss** [comment]
@csmcallister Yeah the Location field is messy sometimes and so probably not worth trying to extract `Venue` names out of. Thinking more about this, I'm inclined to agree that a `Venue` name more specific than the name of a park is probably not necessary for us to straighten out - people can find more details at the event URL. I think I was just trying to get Venues specific enough to assign an address to so people can easily map it and, maybe one day, the website would show a pin on a map. But it seems like that's probably not worth the trouble it would take to make that work reliably, and might not even be possible.

So for these NPS events, I think you're right that just putting '[park name]' as the `Venue` (as you're already doing) and 'National Park Service' as the `Organizer` is enough. Let's just do that.

**Comment by csmcallister** [comment]
Sounds good. But we can still get to having pins on a map, at least with these NPS events, since latitude and longitude is usually returned by the API!

And I’ll try to push changes this afternoon or evening and then share an updated csv.

**Comment by csmcallister** [comment]
closed by bdad7cc
